server:
  port: 8080
#  error:
#    include-exception: false      # Response 에 Exception 을 표시할지
#    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
#    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
#    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_db?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: testsql1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mappings: true
        format_sql: true
        use_sql_comments: true
        show_sql: false
        #          spring entity에 맞는 테이블, 컬럼 자동생성옵션
        #          validate <-  시작시 객체구성과 스키마가 다르다면 예외 발생시킴
        #          update   <-  시작시 entity에 맞는 테이블, 컬럼 자동생성
        hbm2ddl:
          auto: update

logging:
  level:
    org:
      hibernate: info